/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ndeti.procoders;

import edu.ndeti.procoders.models.CartItem;
import edu.ndeti.procoders.models.Product;

/**
 *
 * @author Win7Pro
 */
public class CartItemPanel extends javax.swing.JPanel {

    public CartItemPanel() {
        initComponents();
    }
    
    /**
     * Creates new form CartItemPanel
     */
    public CartItemPanel(CartItem item) {
        super();
        setComponentValues(item);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productNameLabel = new javax.swing.JLabel();
        quantityTextField = new javax.swing.JTextField();
        removeProductButton = new javax.swing.JToggleButton();

        setLayout(new java.awt.GridLayout());

        productNameLabel.setText("Product Name");
        add(productNameLabel);
        add(quantityTextField);

        removeProductButton.setText("Remove");
        add(removeProductButton);
    }// </editor-fold>//GEN-END:initComponents

    private void setComponentValues(CartItem item) {
        productNameLabel.setText(item.getProduct().getName());
        quantityTextField.setText("1");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JToggleButton removeProductButton;
    // End of variables declaration//GEN-END:variables
}
