/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ndeti.procoders;

import edu.ndeti.procoders.models.ShoppingCart;
import edu.ndeti.procoders.exceptions.DuplicatedUsernameException;
import edu.ndeti.procoders.models.CartItem;
import edu.ndeti.procoders.models.Client;
import edu.ndeti.procoders.models.Manager;
import edu.ndeti.procoders.models.Product;
import edu.ndeti.procoders.models.ProductTableModel;
import edu.ndeti.procoders.models.User;
import edu.ndeti.procoders.repositories.ProductsRepository;
import edu.ndeti.procoders.repositories.UsersRepository;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Insets;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ChangeEvent;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author Win7Pro
 */
public class MainForm extends javax.swing.JFrame {

    private User selectedUser;
    private Product selectedProduct;
    private UsersRepository userRepo;
    private ProductsRepository productRepo;
    
    private DefaultListModel<User> usersListModel = new DefaultListModel<>();
    private DefaultListModel<Product> productsListModel = new DefaultListModel<>();
    
    private ProductTableModel productTableModel = new ProductTableModel();
    
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        
        userRepo = UsersRepository.getInstance();
        productRepo = ProductsRepository.getInstance();
        
        updateProductsTable();
        
        userRepo.getUsers().stream().forEach(u -> usersListModel.addElement(u));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();
        usersPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersList = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        middleNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        passwordConfirmField = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        isManagerCheckbox = new javax.swing.JCheckBox();
        cleanButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        ShoppingPanel = new javax.swing.JPanel();
        shoppingPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        productsTableScrollPane = new javax.swing.JScrollPane();
        productsTable = new javax.swing.JTable();
        cartPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        checkoutButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        shoppingItemsScrollPanel = new javax.swing.JScrollPane();
        shoppingItemsPanel = new ShoppingCart(new Client());
        ;
        ProductsPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        productsList = new javax.swing.JList();
        jLabel8 = new javax.swing.JLabel();
        productNameField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        saveProductButton = new javax.swing.JButton();
        cleanProductButton = new javax.swing.JButton();
        deleteProductButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        productDescriptionField = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        productPriceField = new javax.swing.JTextField();
        productImageContainerPanel = new javax.swing.JPanel();
        uploadProductPicButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        logoutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mainTabbedPaneStateChanged(evt);
            }
        });

        usersList.setModel(usersListModel);
        usersList.addListSelectionListener((e) -> {
            Object selectedItem = (User) usersList.getSelectedValue();

            if (selectedItem instanceof User) {
                selectedUser = (User) selectedItem;
                this.firstNameField.setText(selectedUser.getFirstName());
                this.middleNameField.setText(selectedUser.getMiddleName());
                this.lastNameField.setText(selectedUser.getLastName());
                this.usernameField.setText(selectedUser.getUsername());
                this.passwordField.setText(selectedUser.getPasswordHash());
                this.passwordConfirmField.setText(selectedUser.getPasswordHash());
                this.isManagerCheckbox.setSelected(selectedUser.isManager());
            }
        });
        jScrollPane1.setViewportView(usersList);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("User Data");

        jLabel4.setText("Full Name");

        jLabel5.setText("Password");

        jLabel6.setText("Username");

        passwordField.setText("jPasswordField1");

        passwordConfirmField.setText("jPasswordField2");

        jLabel7.setText("Password Confirm");

        isManagerCheckbox.setText("Is Manager");

        cleanButton.setText("Clean");
        cleanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usersPanelLayout = new javax.swing.GroupLayout(usersPanel);
        usersPanel.setLayout(usersPanelLayout);
        usersPanelLayout.setHorizontalGroup(
            usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usersPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(usersPanelLayout.createSequentialGroup()
                                .addGroup(usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(usersPanelLayout.createSequentialGroup()
                                        .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(middleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lastNameField))
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usersPanelLayout.createSequentialGroup()
                                .addGroup(usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(passwordField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameField)
                                    .addComponent(passwordConfirmField, javax.swing.GroupLayout.Alignment.LEADING))
                                .addContainerGap())
                            .addGroup(usersPanelLayout.createSequentialGroup()
                                .addGroup(usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(isManagerCheckbox))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usersPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cleanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        usersPanelLayout.setVerticalGroup(
            usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usersPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(middleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(11, 11, 11)
                        .addComponent(passwordConfirmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(isManagerCheckbox)
                        .addGap(19, 19, 19)
                        .addGroup(usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cleanButton)
                            .addComponent(deleteButton)
                            .addComponent(saveButton))
                        .addGap(0, 73, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        mainTabbedPane.addTab("Users", usersPanel);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Products List");

        productsTable.setModel(productTableModel);
        productsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                productsTableMousePressed(evt);
            }
        });
        productsTableScrollPane.setViewportView(productsTable);
        if (productsTable.getColumnModel().getColumnCount() > 0) {
            productsTable.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout shoppingPanelLayout = new javax.swing.GroupLayout(shoppingPanel);
        shoppingPanel.setLayout(shoppingPanelLayout);
        shoppingPanelLayout.setHorizontalGroup(
            shoppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shoppingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(shoppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productsTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addGroup(shoppingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        shoppingPanelLayout.setVerticalGroup(
            shoppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shoppingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(productsTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Shopping Cart");

        checkoutButton.setText("Checkout");
        checkoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        shoppingItemsScrollPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout shoppingItemsPanelLayout = new javax.swing.GroupLayout(shoppingItemsPanel);
        shoppingItemsPanel.setLayout(shoppingItemsPanelLayout);
        shoppingItemsPanelLayout.setHorizontalGroup(
            shoppingItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );
        shoppingItemsPanelLayout.setVerticalGroup(
            shoppingItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );

        shoppingItemsScrollPanel.setViewportView(shoppingItemsPanel);

        javax.swing.GroupLayout cartPanelLayout = new javax.swing.GroupLayout(cartPanel);
        cartPanel.setLayout(cartPanelLayout);
        cartPanelLayout.setHorizontalGroup(
            cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shoppingItemsScrollPanel)
                    .addGroup(cartPanelLayout.createSequentialGroup()
                        .addComponent(checkoutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearButton))
                    .addGroup(cartPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cartPanelLayout.setVerticalGroup(
            cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shoppingItemsScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkoutButton)
                    .addComponent(clearButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ShoppingPanelLayout = new javax.swing.GroupLayout(ShoppingPanel);
        ShoppingPanel.setLayout(ShoppingPanelLayout);
        ShoppingPanelLayout.setHorizontalGroup(
            ShoppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShoppingPanelLayout.createSequentialGroup()
                .addComponent(shoppingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ShoppingPanelLayout.setVerticalGroup(
            ShoppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(shoppingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab("Shopping", ShoppingPanel);

        productsList.setModel(productsListModel);
        productsList.addListSelectionListener((e) -> {
            Object selectedItem = (Product) productsList.getSelectedValue();

            if (selectedItem instanceof Product) {
                selectedProduct = (Product) selectedItem;
                this.productNameField.setText(selectedProduct.getName());
                this.productDescriptionField.setText(selectedProduct.getDescription());
                this.productPriceField.setText(selectedProduct.getPrice() + "");
                final BufferedImage productImage = selectedProduct.getImage();

                if (productImage != null) {
                    this.productImageContainerPanel.removeAll();
                    this.productImageContainerPanel.add(new ImagePanel(productImage));
                    this.productImageContainerPanel.revalidate();
                    this.productImageContainerPanel.repaint();
                }
            }
        });
        jScrollPane3.setViewportView(productsList);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Product Data");

        jLabel9.setText("Product Name");

        jLabel10.setText("Description");

        saveProductButton.setText("Save");
        saveProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProductButtonActionPerformed(evt);
            }
        });

        cleanProductButton.setText("Clean");
        cleanProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanProductButtonActionPerformed(evt);
            }
        });

        deleteProductButton.setText("Delete");
        deleteProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductButtonActionPerformed(evt);
            }
        });

        productDescriptionField.setColumns(20);
        productDescriptionField.setRows(5);
        jScrollPane2.setViewportView(productDescriptionField);

        jLabel11.setText("Price");

        productImageContainerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        productImageContainerPanel.setLayout(new java.awt.CardLayout());

        uploadProductPicButton.setText("Add Image");
        uploadProductPicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadProductPicButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProductsPanelLayout = new javax.swing.GroupLayout(ProductsPanel);
        ProductsPanel.setLayout(ProductsPanelLayout);
        ProductsPanelLayout.setHorizontalGroup(
            ProductsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProductsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cleanProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(productPriceField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addGroup(ProductsPanelLayout.createSequentialGroup()
                        .addGroup(ProductsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(productNameField))
                        .addGap(18, 18, 18)
                        .addGroup(ProductsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uploadProductPicButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(productImageContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        ProductsPanelLayout.setVerticalGroup(
            ProductsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProductsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductsPanelLayout.createSequentialGroup()
                        .addGroup(ProductsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProductsPanelLayout.createSequentialGroup()
                                .addComponent(productImageContainerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uploadProductPicButton))
                            .addGroup(ProductsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(productNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(ProductsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cleanProductButton)
                            .addComponent(deleteProductButton)
                            .addComponent(saveProductButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainTabbedPane.addTab("Products", ProductsPanel);

        jMenu1.setText("User");

        logoutMenuItem.setText("Logout");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(logoutMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void productsTableMousePressed(MouseEvent evt) {//GEN-FIRST:event_productsTableMousePressed
        final JTable table = (JTable)evt.getSource();
        
        final Point point = evt.getPoint();
        
        final int row = table.rowAtPoint(point);
        final ProductTableModel tableData = (ProductTableModel) table.getModel();
        
        final String itemID = tableData.getValueAt(0, row).toString();
        
        if (evt.getClickCount() == 2 && table.getSelectedRow() != -1) {
            try {
                final Product product = tableData.getProductAt(row);
                final ShoppingCart cart = (ShoppingCart) shoppingItemsPanel;
                
                cart.addItem(product);                
            } catch (IndexOutOfBoundsException exception) {
                final String message = "Failed to add product";
                java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, message, exception);
                JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_productsTableMousePressed

    private void cleanButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cleanButtonActionPerformed
        usernameField.setText("");
        passwordConfirmField.setText("");
        passwordField.setText("");
        firstNameField.setText("");
        middleNameField.setText("");
        lastNameField.setText("");
        isManagerCheckbox.setSelected(false);
        
        selectedUser = null;
    }//GEN-LAST:event_cleanButtonActionPerformed

    private void updateProductsTable() {
        if (productsTable.getModel() instanceof ProductTableModel) {
            final ProductTableModel model = (ProductTableModel) productsTable.getModel();
            
            model.fireTableDataChanged();
        }
    }
    
    private void saveButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (selectedUser != null) {
            JOptionPane.showMessageDialog(this, "Update user feature is not available, please clean the form to create new", "Warn", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        final String password = String.copyValueOf(passwordField.getPassword());
        final String passwordConfirm = String.copyValueOf(passwordConfirmField.getPassword());
        
        if (!password.equals(passwordConfirm)) {
            JOptionPane.showMessageDialog(this, "Password does not match, please make sure that the password is repeated correctly", "Warn", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (isManagerCheckbox.isSelected())
            selectedUser = new Manager();
        else
            selectedUser = new Client();
        
        selectedUser.setFirstName(firstNameField.getText());
        selectedUser.setMiddleName(middleNameField.getText());
        selectedUser.setLastName(lastNameField.getText());
        selectedUser.setUsername(usernameField.getText());
        
        final String passwordText = String.copyValueOf(passwordField.getPassword());
        
        selectedUser.setPassword(passwordText);
        
        try {
            userRepo.addUser(selectedUser);    
            usersListModel.addElement(selectedUser);
            usersList.setModel(usersListModel);
            
            JOptionPane.showMessageDialog(this, "User Created", "Info", JOptionPane.INFORMATION_MESSAGE);
            
            cleanButtonActionPerformed(evt);
        } catch (DuplicatedUsernameException exception) {
            final String message = "Failed to save new user, there is a user with same username";
            JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, message, exception);
        } finally {
            selectedUser = null;
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    
    private void deleteButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed

        if (selectedUser == null) {
            JOptionPane.showMessageDialog(this, "User must be selected from list to remove", "Warn", JOptionPane.WARNING_MESSAGE);    
            return;
        }
        
        userRepo.removeUser(selectedUser);
        usersListModel.removeElement(selectedUser);
        usersList.setModel(usersListModel);

        JOptionPane.showMessageDialog(this, "User Removed", "Info", JOptionPane.INFORMATION_MESSAGE);
        
        selectedUser = null;
        cleanButtonActionPerformed(evt);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void saveProductButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_saveProductButtonActionPerformed
        if (selectedProduct != null) {
            JOptionPane.showMessageDialog(this, "Update product feature is not available, please clean the form to create new", "Warn", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            selectedProduct = new Product();
        
            selectedProduct.setName(productNameField.getText());
            selectedProduct.setDescription(productDescriptionField.getText());
            selectedProduct.setPrice(Double.parseDouble(productPriceField.getText()));

            final Component imageComponent = productImageContainerPanel.getComponent(0);

            if (imageComponent instanceof ImagePanel) {
                final ImagePanel imageConainter = (ImagePanel) imageComponent;
                selectedProduct.setImage(imageConainter.getBufferedImage());
            }
            
            productRepo.addProduct(selectedProduct);
            
            JOptionPane.showMessageDialog(this, "Product Created", "Info", JOptionPane.INFORMATION_MESSAGE);
            
            productsListModel.addElement(selectedProduct);
            productsList.setModel(productsListModel);
            
            cleanProductButtonActionPerformed(evt);
        } catch (Exception exception) {
            final String message = "Failed to save new product";
            JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, message, exception);
        } finally {
            selectedProduct = null;
        }
    }//GEN-LAST:event_saveProductButtonActionPerformed

    private void cleanProductButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cleanProductButtonActionPerformed
        productNameField.setText("");
        productDescriptionField.setText("");
        
        productPriceField.setText("");
        
        productImageContainerPanel.removeAll();
        productImageContainerPanel.revalidate();
        productImageContainerPanel.repaint();
        
        selectedProduct = null;
    }//GEN-LAST:event_cleanProductButtonActionPerformed

    private void deleteProductButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_deleteProductButtonActionPerformed
        if (selectedProduct == null) {
            JOptionPane.showMessageDialog(this, "Product must be selected from list to remove", "Warn", JOptionPane.WARNING_MESSAGE);    
            return;
        }
        
        productRepo.removeProduct(selectedProduct);
        productsListModel.removeElement(selectedProduct);
        productsList.setModel(productsListModel);

        JOptionPane.showMessageDialog(this, "Product Removed", "Info", JOptionPane.INFORMATION_MESSAGE);
        
        selectedProduct = null;
        cleanProductButtonActionPerformed(evt);
    }//GEN-LAST:event_deleteProductButtonActionPerformed

    private void uploadProductPicButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_uploadProductPicButtonActionPerformed
        try {
            JFileChooser fileChooser = new JFileChooser();
            
            fileChooser.setAcceptAllFileFilterUsed(false);
            fileChooser.setMultiSelectionEnabled(false);
            
            FileNameExtensionFilter restrictImagesOnly = new FileNameExtensionFilter("Only Image Files", ImageIO.getReaderFileSuffixes());
            
            fileChooser.addChoosableFileFilter(restrictImagesOnly);
            
            final int dialogState = fileChooser.showDialog(this, "Open");
            
            if (dialogState == JFileChooser.APPROVE_OPTION) {
                final File file = fileChooser.getSelectedFile().getAbsoluteFile();
                BufferedImage image = ImageIO.read(file);

                productImageContainerPanel.removeAll();
                productImageContainerPanel.add(new ImagePanel(image));
                productImageContainerPanel.revalidate();
                productImageContainerPanel.repaint();
            }

        } catch (Exception exception) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, "Failed to load product image", exception);
        }
    }//GEN-LAST:event_uploadProductPicButtonActionPerformed

    private void mainTabbedPaneStateChanged(ChangeEvent evt) {//GEN-FIRST:event_mainTabbedPaneStateChanged
        java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, "Tab Changed");

        updateProductsTable();
    }//GEN-LAST:event_mainTabbedPaneStateChanged

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        shoppingItemsPanel.removeAll();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        javax.swing.JFrame loginFrame = new LoginFrame();
        
        loginFrame.setDefaultCloseOperation(EXIT_ON_CLOSE);
        loginFrame.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void checkoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutButtonActionPerformed
        final int result = JOptionPane
                .showConfirmDialog(this, 
                        "The order total is: " + 
                                ((ShoppingCart) shoppingItemsPanel)
                                        .getTotalCartValue().toString() 
                                + "\n Do you want to continue?", 
                        "Checkout", JOptionPane.YES_NO_OPTION);
        
        if (result == JOptionPane.YES_OPTION) {
            JOptionPane
                    .showMessageDialog(this, 
                            "Thanks for ordering, your order will be processed", 
                            "Checkout", JOptionPane.INFORMATION_MESSAGE);

            clearButtonActionPerformed(evt);
        } else {
            JOptionPane.showMessageDialog(this, "Your order was canceled");
        }        
    }//GEN-LAST:event_checkoutButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ProductsPanel;
    private javax.swing.JPanel ShoppingPanel;
    private javax.swing.JPanel cartPanel;
    private javax.swing.JButton checkoutButton;
    private javax.swing.JButton cleanButton;
    private javax.swing.JButton cleanProductButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton deleteProductButton;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JCheckBox isManagerCheckbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JMenuItem logoutMenuItem;
    public javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JTextField middleNameField;
    private javax.swing.JPasswordField passwordConfirmField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextArea productDescriptionField;
    private javax.swing.JPanel productImageContainerPanel;
    private javax.swing.JTextField productNameField;
    private javax.swing.JTextField productPriceField;
    private javax.swing.JList productsList;
    private javax.swing.JTable productsTable;
    private javax.swing.JScrollPane productsTableScrollPane;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton saveProductButton;
    private javax.swing.JPanel shoppingItemsPanel;
    private javax.swing.JScrollPane shoppingItemsScrollPanel;
    private javax.swing.JPanel shoppingPanel;
    private javax.swing.JButton uploadProductPicButton;
    private javax.swing.JTextField usernameField;
    private javax.swing.JList usersList;
    private javax.swing.JPanel usersPanel;
    // End of variables declaration//GEN-END:variables
}
